### PR TITLE
Fix #596 and #598: error profiling throughput grid on aws and gcp 

### LINKED ISSUE #596: Error profiling throughput grid for Skyplane on AWS
From #595 

Only profiling AWS: `skyplane experiments throughput-grid --no-enable-azure --no-enable-gcp --no-enable-gcp-standard`

Error: 
```
19:40:55 [INFO]  Provisioning AWS instances in ['eu-north-1', 'ap-south-1', 'eu-west-3', 'eu-west-2', 'eu-west-1', 'ap-northeast-3', 'ap-northeast-2', 'ap-northeast-1', 
'sa-east-1', 'ca-central-1', 'ap-southeast-1', 'ap-southeast-2', 'eu-central-1', 'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2']
⠦ Add IP to aws security groups ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/17 0:00:0219:40:58 [ERROR] Error running add_ips_to_security_group: 'NoneType' object is not iterable
⠇ Add IP to aws security groups ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/17 0:00:0319:40:58 [ERROR] Error running add_ips_to_security_group: 'NoneType' object is not iterable
⠹ Add IP to aws security groups ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/17 0:00:0319:40:58 [ERROR] Error running add_ips_to_security_group: 'NoneType' object is not iterable
19:40:58 [ERROR] Error running add_ips_to_security_group: 'NoneType' object is not iterable
19:40:58 [ERROR] Error running add_ips_to_security_group: 'NoneType' object is not iterable
...
```

### PR DESCRIPTION
**Pull request by lynnliu030**
This is the PR to fix #596 and #598 with added functionality to overwrite the default AMI to ubuntu for profiling. Also edit the firewall rule on GCP to allow iperf3 connections and use private IPs for within-GCP throughput profile 

There're some minor errors with package installation and image & host platform mismatch when building from source with docker on Mac M1, include the fix here as well.

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -5,6 +5,7 @@ FROM python:3.10-slim
 RUN --mount=type=cache,target=/var/cache/apt apt update \
     && apt-get install --no-install-recommends -y curl ca-certificates stunnel4 \
     && apt-get clean \
+    && apt-get -y install gcc mono-mcs \
```
Comment (parasj) [inline Dockerfile:8]: Merge with line 6

File: scripts/pack_docker.sh [hunk 2]
```diff
@@ -12,7 +12,7 @@ set +e
 
 >&2 echo -e "${BGreen}Building docker image${NC}"
 set -e
->&2 sudo DOCKER_BUILDKIT=1 docker build -t skyplane .
+>&2 sudo DOCKER_BUILDKIT=1 docker build -t skyplane --platform linux/x86_64 .
```
Comment (parasj) [inline scripts/pack_docker.sh:15]: Is this for building cross platform images on M1? pretty neat!

File: skyplane/compute/aws/aws_cloud_provider.py [hunk 3]
```diff
@@ -333,11 +338,19 @@ def provision_instance(
...
     ) -> AWSServer:
         assert not region.startswith("aws:"), "Region should be AWS region"
         if name is None:
             name = f"skyplane-aws-{str(uuid.uuid4()).replace('-', '')}"
         iam_instance_profile_name = f"{name}_profile"
+
+        # set default image used for provisioning instances in AWS
+        if instance_os == "ubuntu":
+            image_id = "resolve:ssm:/aws/service/canonical/ubuntu/server/bionic/stable/current/amd64/hvm/ebs-gp2/ami-id"
+        else:  # default: "aws-linux-2"
```
Comment (parasj) [inline skyplane/compute/aws/aws_cloud_provider.py:351]: Make explicit and raise an error if not matched, also rename to ecs-aws-linus-2

File: skyplane/compute/aws/aws_server.py [hunk 4]
```diff
@@ -26,6 +26,15 @@ def __init__(self, region_tag, instance_id, log_dir=None):
         self.instance_id = instance_id
         self.local_keyfile = key_root / "aws" / f"skyplane-{self.aws_region}.pem"
 
+        # update the login name according to AMI
```
Comment (parasj) [inline skyplane/compute/aws/aws_server.py:29]: Move to a cached property so that it's lazily queried

```python
@property
@functools.lru_cache
def login_name(self) -> str:
```

File: skyplane/compute/gcp/gcp_cloud_provider.py [hunk 5]
```diff
@@ -318,6 +323,11 @@ def provision_instance(
         with open(os.path.expanduser(self.public_key_path)) as f:
             pub_key = f.read()
 
+        if instance_os == "ubuntu":
+            image = "projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts"
+        else:  # default: cos
```
Comment (parasj) [inline skyplane/compute/gcp/gcp_cloud_provider.py:328]: Make check explicit, else raise ValueError

File: skyplane/replicate/replicator_client.py [hunk 6]
```diff
@@ -576,8 +576,6 @@ def monitor_transfer(
                         # check for errors and exit if there are any (while setting debug flags)
                         errors = self.check_error_logs()
                         if any(errors.values()):
-                            copy_gateway_logs = True
```
Comment (parasj) [inline skyplane/replicate/replicator_client.py:579]: Why do we not copy errors upon an error? I'm OK with commenting out write_profile but write_gateway_logs is useful

**Review by parasj — APPROVED** [review]
LGTM

File: Dockerfile (hunk 1 above)
Comment (parasj) [inline Dockerfile:8]: Why do you add `mono-mcs` and `gcc`?

File: skyplane/replicate/replicator_client.py (hunk 6 above)
Comment (lynnliu030) [reply skyplane/replicate/replicator_client.py:579]: We can keep it, I think this is auto-removed when I run `autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive skyplane`?

File: scripts/pack_docker.sh (hunk 2 above)
Comment (lynnliu030) [reply scripts/pack_docker.sh:15]: Yeah! This fixes the error: `The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested`
